# Generated by Django 5.0.1 on 2024-01-31 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user',
        ),
    ]
